### ISSUE TITLE
Compile errors when using -Werror=format-security (default in Fedora Linux)

### ISSUE THREAD

**Issue by dev4inno** [mridoni/gix#100]
Hello Marco,

as requested by Simon Sobisch, here are the compile errors in Fedora Linux (I commented out every line in error stepwise to get all errors):

(1) Source Member: gix-common/ServerConfig.cpp

```
ServerConfig.cpp:72:33: error: format not a string literal and no format arguments [-Werror=format-security]
   72 |                         qWarning(msg.toUtf8().constData());
ServerConfig.cpp:81:60: warning: 'QHostAddress& QHostAddress::operato
```

(2) Source Member: gix-http/main.cpp

```
main.cpp:98:32: error: format not a string literal and no format arguments [-Werror=format-security]
   98 |                         fprintf(stderr, QString("Cannot find config file").toUtf8().constData());
      |                         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:120:16: error: format not a string literal and no format arguments [-Werror=format-security]
  120 |         fprintf(stdout, qPrintable(text));
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:126:24: error: format not a string literal and no format arguments [-Werror=format-security]
  126 |                 fprintf(stderr, qPrintable(text));
      |                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```

I guess Fedora is more strict than Ubuntu/Debian because is serves as a testing and pre-release of Redhat Enterprise Linux, which uses Fedora as it's basis and is in use by large companies.

Ciao
Klaus

**Comment by GitMensch** [comment]
That's not Fedora, but the actual check. Those are "common" issues, adding a "%s", after the stream (stdout/stderr) fixes those.

**Comment by dev4inno** [comment]
Thank you Simon.

So these changes are required:

(1) Source Member: gix-common/ServerConfig.cpp

`   72 |                         qWarning("%s", msg.toUtf8().constData());
`

(2) Source Member: gix-http/main.cpp

```
   98 |                         fprintf(stderr, "%s", QString("Cannot find config file").toUtf8().constData());

  120 |         fprintf(stdout, "%s", qPrintable(text));

  126 |                 fprintf(stderr, "%s", qPrintable(text));
```

I applied them in the local source and the compile errors are gone.

**Comment by mridoni** [comment]
Ok, I will apply them in the next few days (I will be out of town until next Tuesday).

By the way: to make it quicker, fixes like this will be directly integrated in the source tree, without having to perform a full release and build all the packages. This was mainly the rationale behind the repository split, though obviously new releases will be still published when needed (or requested) or anyway after a certain amount of time has passed or enough fixes/features have accumulated (and the time left free from my day-job allows).
