### ISSUE TITLE
clean up relation of gix-http to QtWebApp

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#11]
From a quick glance it seems that gix-http is a (partial?) fork of https://github.com/StefanFrings/QtWebApp.
The question is: What version is it based on (especially because of its license, the first version in that repo (1.7.5) is LGPLv3+.

A further question then is: wouldn't it be more reasonable to create an official fork via GitHub and then commit the changes for gix-http there? This would bring in the benefit of its full history, full attribution and the option to pull in changes from "upstream" (or even pull changes into it more easy) later... and provide a nice option for an additional "split" of this repo (possibly with a git submodule) which again will lead to a smaller local clone if wanted.

**Comment by mridoni** [comment]
This is a good idea, but it implies a reorganization of my workflow: at the moment the "work repository" is a private one on Subversion (which is what I normally use). This is backed up and manually synced on release with the one on Github and another server that acts as a build server.

As it is obvious, this is quite complicated to maintain, so I am planning to switch development of Gix-IDE totally to Git, but this will have to wait until a few things have been stabilized and/or improved.

With regard to attribution: I'll be working on cleaning up the licenses (Issue #2) to make it clearer.

**Comment by GitMensch** [comment]
If you want to add a license note to gix-http I suggest to include something like the following in those files:

```
/*
   Copyright (C) 2010-2021 Stefan Frings.

   This file is part of QtWebApp.

   QtWebApp is free software: you can redistribute it and/or modify it
   under the terms of the GNU Lesser General Public License as published
   by the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   QtWebApp is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with QtWebApp.
   If not, see <https://www.gnu.org/licenses/>.
*/
```

... and where the files had non-trivial changes from you add your copyright note below.

In any case I suggest (also for attribution) to include a similar note as you had with OCesql in the main README also for the HTTP-Part (possibly having both references as link to its repos).

When the workflow change is done (I totally understand that this takes time and is not a high priority currently) I suggest to make a "hard cut" with gix-http:

* fork the original repo (= use whatever is currently then)
* create a new branch and make it the new default (keeping the old for possibly sync)
* delete the files that are not relevant to gix-http (if any)
* apply your changes on top of this (which I understand are in a svn repository - so you can get those changes out as a patch; if you need help with that just drop a note) 
* then replace the old included version with the new updated one (likely as git submodule)
* if needed: adjust it further

**Comment by GitMensch** [comment]
Closing this because the attribution was handled with #2 and the split will be done later, and is unlikely to be done soon which is the reason that I've created #14 for that.

**Comment by GitMensch** [comment]
Ping on the adjusted workflow and then split - directly after a release sounds like the best option available.
Note: because of one missing feature and some minor bugs (and bad error handling) I'm in the process of updating an ocesql fork, it would be nice to be possibly able to share the result with gix-sql.

**Comment by mridoni** [comment]
> Note: because of one missing feature and some minor bugs (and bad error handling) I'm in the process of updating an ocesql fork, it would be nice to be possibly able to share the result with gix-sql.

I'll look into it, but I don't think this is really possible without a ton of work: as I said GixSQL isn't a simple fork of ocesql, it started there for sure, but the internals have simply changed too much in the transition towards GixSQL, and things like cursor handling or the grammar itself, beside many others, have been almost completely rewritten or profoundly modified, and a substantial part of the code is now C++, not C anymore.
