### ISSUE TITLE
GIX-IDE vs GIX-SQL do i need both?

### ISSUE THREAD

**Issue by aoirthoir** [mridoni/gix#121]
In regards to GIX-IDE. If I have that do I also need to install GIX-SQL if I want to make use of GIX-SQL features, or are they built into GIX-IDE also?

If there  is a forum that these questions should be asked on, I'll post it there if someone gives me the links.

Thanks kindly in advance,
Aoirthoir

**Comment by mridoni** [comment]
Hello, Gix-IDE includes GixSQL with the command-line preprocessor tools and runtime libraries, so there is no need to install it separately, unless you need to install it this way for a specific task. You should find the preprocessor (`gixpp`) in the `bin` subdirectory of Gix-IDE's install path (normally `C:\Program Files\Gix-IDE` or `C:\Program Files (x86)\Gix-IDE` on Windows, or `/opt/gix-ide` on Linux). The runtime/link libraries are in the `lib` subdirectory tree. The various versions of the libraries are divided by platform (`x86` or `x64`) and (on Windows only) compiler type (`msvc` or `gcc`).

**Comment by mridoni** [comment]
> Thank you for the answer. Another question, if I install GIX-IDE do I need a separate install of GnuCOBOL or are you distributing that together.

For Windows there is a package that contains binary packages of GnuCOBOL 3.1.2 and their runtimes dependencies (or you can use your own install of GnuCOBOL). For Linux you need to install it yourself. Unfortunately, at the moment, distribution-provided installs of GnuCOBOL cannot be automatically configured in Gix-IDE and a "manual" install directory must be provided. This was not really important as long as the main distributions were providing old versions of GnuCOBOL (mainly 2.2) that were not suitable for debugging in Gix-IDE anyway. As things starting moving on this will obviously be fixed as soon as possible. 

> And yet one last one, is there a forum that is a better place to ask questions regarding GID-IDE? With the title being ISSUES this seemed to me, tho I might be wrong, a place to log issues or problems rather than ask questions?

Not yet, but if the traffic here grows beyond what is manageable, there will be probably be one. For now, if you have "generic" questions, just prefix the issue with "Q" or "Question" or, if they are not of general interest, write me a mail (the address is on the project page).

Thanks
