### ISSUE TITLE
GnuCOBOL version parsing from cobc is broken

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#128]
I've started Gix-IDE and setup GC 2.2 x86; I've then added GC 3.2 x64 later and have it enabled as current configuration under Settings->GnuCOBOL.

Using "Debugging"  still shows:

~~~
Debugging is only supported when using GnuCOBOL 3.1.2 or greater
~~~

The output pane has no information about the failed debug-start:

~~~
Initializing compiler manager
Parsing compiler definition for [comp_14576], platform: x86
Added platform x86 for GC 2.2. MinGW NoDB
Added compiler GC 2.2. MinGW NoDB
Parsing compiler definition for [comp_31752], platform: x64
Added platform x64 for GC 3.2 x64 GCC (MSYS2)
Added compiler GC 3.2 x64 GCC (MSYS2)
 ~~~

**Comment by mridoni** [comment]
This is probably a parsing error somwhere: GnuCOBOL 3.2, though not actually tested (yet), should technically pass the version test, and in all evidence it doesn't.

I am flagging this as a bug and will start working on it.

Thanks

**Comment by mridoni** [comment]
Can you post here the .def file for the compiler? It should be `comp_31752.def`

Thanks

**Comment by GitMensch** [comment]
Here you go with both. Maybe it got confused by `2-dev` in `3.2-dev.0` (then likely will also with "-rc1", "-beta", "preview", ...

[comp_14576.def](https://github.com/mridoni/gix/files/9982138/comp_14576.def.txt)
[comp_31752.def](https://github.com/mridoni/gix/files/9982139/comp_31752.def.txt)

**Comment by mridoni** [comment]
> Here you go with both. Maybe it got confused by `2-dev` in `3.2-dev.0` (then likely will also with "-rc1", "-beta", "preview", ...

That's probably it. Thanks.

**Comment by mridoni** [comment]
This should be fixed with the commit mentioned above.

**Comment by GitMensch** [comment]
That looks good. Note for the other checks (as noted in #127) it seems necessary to export LANG before executing ` cobc --info`.

**Comment by GitMensch** [comment]
I _guess_ that this is solved now and _possibly_ `LANG=C` is now also set before doing any calls to cobc for version/info parsing.
