### ISSUE TITLE
FR: make it so that the installer doesn't need admin privileges

### ISSUE THREAD

**Issue by bmnascimento** [mridoni/gix#129]
Are there any big hurdles with the installer that prevents it from having a user installation only?

Unfortunately at my work the environment is very locked down, so I can't install it due to not having admin rights.

I'm willing to take a look at the code and try to make a PR if this is deemed a desired feature.

**Comment by GitMensch** [comment]
Sounds very useful to me. Maybe @mridoni could also provide a ".zip" installation (packing without installer, directly before it is built, allowing "portable" use)?

**Comment by mridoni** [comment]
This should be possible with a few changes to the installer, provided that one does not need to install the MSVC runtimes/build tools. I need to verify it, but in the meantime can you file an issue here here on GitHub?

Thanks

**Comment by bmnascimento** [comment]
Yeah, sure! Thank you very much
