### ISSUE TITLE
Window size too small for input data

### ISSUE THREAD

**Issue by MrT201509** [mridoni/gix#137]
I installed gix-ide under Windows 11 with paralles desktop on my Macbook Air 15.

The window size is too small and I can't change it. So I see not all fields. It is the same when I open "manage settings".

See attatched file.

What can I do?

![image](https://github.com/mridoni/gix/assets/40859924/0d401261-867e-4b48-98f1-ab74fd06e170)

**Comment by mridoni** [comment]
Hello, sorry but the testing on Windows 11 at the moment is still minimal  (yes, I know, and again: sorry for that. There is a "Screen resolution" setting in Appearance/Misc display settings, you can try it. I it's mainly there account for th different DPIs/screen sizes in Linux, since I couldn't find a way to make Qt give me reliable cross-platform measurements, but it is also honored on Windows.

![image](https://github.com/mridoni/gix/assets/16079316/f6843586-fae0-4992-a785-b57b2a051c9e)

**Comment by MrT201509** [comment]
Leider bringt diese Einstellung auch nicht den gewünschten Erfolg. Alle anderen sichtbaren Frames lassen sich hierdurch ein "wenig" vergrößern. Nur leider nicht bei den aufgerufenen modalen Dialogen. Welches ist denn die bevorzugte Architektur (Windows, Linux, MacOS, usw.)?
![image](https://github.com/mridoni/gix/assets/40859924/50460114-3309-4f9a-8760-4e7ac1187d36)
![image](https://github.com/mridoni/gix/assets/40859924/5a4e4cae-989c-4d44-997f-4096b5ece0c1)

**Comment by mridoni** [comment]
It is mainly tested on Windows, then on Linux). There is no current port for macOS.

**Comment by MrT201509** [comment]
Dann sollte es auch keine Probleme geben, oder? Aber meine Installation funktioniert bei den modalen Dialogen nicht. Und warum schreibst du, dass die Tests unter Windows zurzeit nicht sehr umfänglich waren?
Kann ich denn irgendetwas tun, um die Dialoge lesbar zu machen? Vielen Dank für deine Antworten.

**Comment by MrT201509** [comment]
Ich habe das Problem behoben! 
In Parallels Desktop habe ich die Konfiguration der VM für Windows angepasst. 
Unter "Hardware -> Grafiken" habe ich die Auflösung von "Optimal für Retina-Display (Hochauflösung)" nach "Skaliert (Grafik auf volle Größe") geändert ("Optimal für Altanwendungen").

Und so sieht ein modales Dialog-Fenster jetzt aus:
![image](https://github.com/mridoni/gix/assets/40859924/86d55dfe-4064-4a40-a0ad-d502a06945e9)

**Comment by GitMensch** [comment]
Thanks for the note; so as "kind of expected" it was the (default) High-DPI setting in the VM settings. Soeone should check if HighDPI works on Windows using that version of QT...
