### ISSUE TITLE
Cannot find the compiler directory

### ISSUE THREAD

**Issue by proteomis** [mridoni/gix#18]
Hello,
I installed GnuCobol 3.1.2 under windows 10 from the binaries available on arnoldtrembley.com. It seems ok !
![2021-03-19-gnu](https://user-images.githubusercontent.com/30907300/111793269-63d88080-88c5-11eb-8d9e-0bad6450b369.jpg)

Then, I installed Gix-IDE without compiler and the introduced the required directories to configure the compiler.
![Capture-config](https://user-images.githubusercontent.com/30907300/111793373-7f438b80-88c5-11eb-85cc-53b465a0e738.PNG)

And when I click on OK, I have an error message "Cannot find the compiler directory, please check you configuration".
![Capture-err](https://user-images.githubusercontent.com/30907300/111793514-a437fe80-88c5-11eb-99c5-9ec8812a2fa1.PNG)

But I can call the cobc compiler from the command line. I ran the setenv command, so the compiler can be called easily.

I do not see why I get this error and how to solve it! Any idea ?

Regards,

Alain

**Comment by mridoni** [comment]
This has already been resolved, the fix will be in the next binary release (in a few days).

**Comment by GitMensch** [comment]
Is this fixed in v1.0.1's 947d4a5599de15d83077a9380f8f7e247b83e813 (and can therefore be closed)?

**Comment by proteomis** [comment]
Bug fixed.
Thank you!
