### ISSUE TITLE
High DPI screen result in tiny toolbar icons and garbled dialog boxes

### ISSUE THREAD

**Issue by IanWorthington** [mridoni/gix#32]
After fiddling with the compatibility properties the following seems to improve matters:

![image](https://user-images.githubusercontent.com/5931335/141030821-afc3851a-e066-4d49-bdc6-df439703b108.png)

**Comment by mridoni** [comment]
Unfortunately I don't have a high-DPI screen to test this with at the moment, but I'll try to find a solution (Qt is supposed to handle this in a semi-automatic-fashion, but in all evidence it doesn't).

**Comment by mridoni** [comment]
I have added a "Screen resolution" setting (it will be part of v1.0.9) that allows to manually set a screen resolution. This is probably solvable in a more "automatic" fashion on Windows, but there are some difficulties on Linux (different DPIs and window managers, etc.).

In the meantime you can set the QT_FONT_DPI environment variable to a suitable value before launching Gix-IDE, e.g.

    set QT_FONT_DPI=144
    "%ProgramFiles%\Gix-IDE\bin\gix-ide.exe"

Obviously, you can also set it in the "Enviroment Variables" section in System Properties, but this will also affect all the other Qt applications.

**Comment by mridoni** [comment]
This Is fixed in the current releases: a new entry in Settings -> Appearance allows to specify  acustom DPI setting
