### ISSUE TITLE
GixSql: How to adjust client encoding?

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#39]
Currently this is set to a fixed value https://github.com/mridoni/gix/blob/21e5e6ab13d94ca454881d84bf5bf73eb74501bf/gixsql/libgixsql/gixsql.cpp#L191 and passed to the db client.

Would it be possible to override this via COBOL (the connection string handling seems reasonable)?

As a reference: "upstream" had `SJIS` as default but the option to override it via environment variable `OCDB_DB_CHAR`.

**Comment by mridoni** [comment]
Starting from [v1.0.8](https://github.com/mridoni/gix/releases/tag/v1.0.8) it is possible to add the corresponding connection parameter. Defaults to UTF8 as usual.

**Comment by GitMensch** [comment]
That sounds reasonable - but somehow my data connection string only works when I don't add the client encoding:

connects `pgsql://myserver:54321/dbname`
raises sqlerror -201: `pgsql://myserver:54321/dbname?client_encoding=LATIN9`

if my debugging did not fail me - the second one fails the `regex_match()` in `DataSourceInfo::init()`)

I must make something wrong, but I don't know what.

**Comment by GitMensch** [comment]
Ah, just found with debugging that there is an undocumented `GIXSQL_CLIENT_ENCODING` now - so using this for now and creating an issue for the documentation, I'd still like to know what the issue with the datasource above is.

**Comment by mridoni** [comment]
> connects pgsql://myserver:54321/dbname
> raises sqlerror -201: pgsql://myserver:54321/dbname?client_encoding=LATIN9
> if my debugging did not fail me - the second one fails the regex_match() in DataSourceInfo::init())
> I must make something wrong, but I don't know what.

No, it was a problem in the regular expression definition, it is fixed now and it will be in v1.0.11. I am reopening the issue until this solution is confirmed to work.
