### ISSUE TITLE
Suggestion: remove external libraries, possibly use git-submodules and gitignore the binaries

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#4]
Just a suggestion... the reasoning behind this:

* a local clone (can be) much smaller
* the external libraries are directly seen as those, including their history if one likes to

For Scintilla it seems reasonable to use a git mirror - https://github.com/RaiKoHoff/scintilla seems to be always on the latest release - as [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).
[libdwarf](https://sourceforge.net/projects/libdwarf/) uses git, so it may be possible to directly use it as submodule (using the appropriate subfolder).

... in any case I suggest to have the binaries from those in .gitignore (currently they are for Win32 only and in any case add up to the repo size again).

**Comment by mridoni** [comment]
As I refine the build process for all the platforms, binaries will be completely removed from the repository and libraries will be built in place where needed (i.e. libdwarf comes already packaged under Linux, so there is no need to build it there). With regard to using other repositories as sub-modules, for now I prefer to track them manually and directly include the code (with the proper license and copyright attributions, of course). This might change as the situation evolves but for now it makes the work easier.
