### ISSUE TITLE
Please provide a release source tarball

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#42]
Ideally one for both the full gixide and for gixsql.
This would have all generated files in (especially Bison and Flex come to mind - with the generated files distribution in _release_ tar files the dependency on theses tools for the user would be removed (related: #41).

**Comment by GitMensch** [comment]
Reference: https://sourceforge.net/p/gnucobol/discussion/contrib/thread/dcee65a178/?limit=25#dd18/b82c/3389

@mridoni wrote:
>  I'll try to add a build script to generate the .tar.gz source package in the next few days.

I guess that's already done locally, just not pushed to the repo here. Along with adding it to the repo it would be good to also have a .tar.gz for GixIDE (complete) and GixSQL (separate, as it is nicely done with the .deb files) uploaded in the releases.

**Comment by mridoni** [comment]
Introduced in [v1.0.8](https://github.com/mridoni/gix/releases/tag/v1.0.8)
