### ISSUE TITLE
Gix-IDE v1.0.7 Debugger crashes 

### ISSUE THREAD

**Issue by dev4inno** [mridoni/gix#48]
Just made a fresh install with the .deb packages under Ubuntu 20.04:

Gix-IDE v1.0.7-1462 
Ubuntu 20.04 Version 20.04.3 LTS (Focal Fossa) 64-bit.

Created a new project with this tiny program and added a break point as marked:

Test1.cbl

`

       IDENTIFICATION DIVISION.
       
       PROGRAM-ID. TEST1.

       ENVIRONMENT DIVISION.
       
       INPUT-OUTPUT SECTION.
       
       FILE-CONTROL.
       
       DATA DIVISION.
       
       FILE SECTION.
       
       WORKING-STORAGE SECTION.
       01 myfield pic x(5) value 'Break'.
       LINKAGE SECTION.
            
            01  PAR1      PIC X(255).
            01  PAR2      PIC 9(12).
      
       PROCEDURE DIVISION.

           display myfield.      *>> break point here
           DISPLAY 'HELLO WORLD'.  
`
Result:

Setting up console
Starting process
Process started (9862)
Symbols loaded
Waiting for signal
Got signal: 1407
Got signal 5 (Trace/breakpoint trap)
Breakpoint 0 hit
Load address for PID 9862: 0x000055de7792b000 (raw: 55de7792b000)
Installing breakpoint at 0x55de7792c200 - old data: 0x8949ed31fa1e0ff3, new data : 0x8949ed31fa1e0fcc, saved data: f3
Installing breakpoint at 0x55de7792c486 - old data: 0xbffffffcc5e8, new data : 0xbffffffcc5cc, saved data: e8
Installing breakpoint at 0x55de7792c4d2 - old data: 0xe800000b6f3d8d48, new data : 0xe800000b6f3d8dcc, saved data: 48
Trying to register COBOL module TEST1 from /home/haegar/source/gnucobol/gixide/test1/bin/debug/x64/TEST1
Installing breakpoint at 0x55de7792c31e - old data: 0xe5894855fa1e0ff3, new data : 0xe5894855fa1e0fcc, saved data: f3
IDE is resolving user breakpoints (1 user breakpoint(s) received)
IDE says: user breakpoint at 24@/home/haegar/source/gnucobol/gixide/test1/TEST1.cbl
Resolving rendezvous address
Linker breakpoint (rendezvous) address is (nil)
Error (5) Input/output error
Installing breakpoint at (nil) - old data: 0xffffffffffffffff, new data : 0xffffffffffffffcc, saved data: ff
Breakpoint 0 processing finished
Waiting for signal
Got signal: 1407
Updating list of loaded libraries
Resolving rendezvous address
Linker breakpoint (rendezvous) address is 0x7f619eea51d0
Installing breakpoint at 0x7f619eea51d0 - old data: 0x2e6666c3fa1e0ff3, new data : 0x2e6666c3fa1e0fcc, saved data: f3
Loaded /lib/x86_64-linux-gnu/libc.so.6 at 0x7f619ec09000
Loading library /lib/x86_64-linux-gnu/libc.so.6
Loaded /lib/x86_64-linux-gnu/libdl.so.2 at 0x7f619e92a000
Loading library /lib/x86_64-linux-gnu/libdl.so.2
Loaded /lib/x86_64-linux-gnu/libgcc_s.so.1 at 0x7f619c8cd000
Loading library /lib/x86_64-linux-gnu/libgcc_s.so.1
Loaded /lib/x86_64-linux-gnu/libgmp.so.10 at 0x7f619eb85000
Loading library /lib/x86_64-linux-gnu/libgmp.so.10
Loaded /lib/x86_64-linux-gnu/libicudata.so.66 at 0x7f619caed000
Loading library /lib/x86_64-linux-gnu/libicudata.so.66
Loaded /lib/x86_64-linux-gnu/libicuuc.so.66 at 0x7f619e744000
Loading library /lib/x86_64-linux-gnu/libicuuc.so.66
Loaded /lib/x86_64-linux-gnu/liblzma.so.5 at 0x7f619e6ff000
Loading library /lib/x86_64-linux-gnu/liblzma.so.5
Loaded /lib/x86_64-linux-gnu/libm.so.6 at 0x7f619e5b0000
Loading library /lib/x86_64-linux-gnu/libm.so.6
Loaded /lib/x86_64-linux-gnu/libncursesw.so.6 at 0x7f619e991000
Loading library /lib/x86_64-linux-gnu/libncursesw.so.6
Loaded /lib/x86_64-linux-gnu/libpthread.so.0 at 0x7f619caca000
Loading library /lib/x86_64-linux-gnu/libpthread.so.0
Loaded /lib/x86_64-linux-gnu/libstdc++.so.6 at 0x7f619c8e8000
Loading library /lib/x86_64-linux-gnu/libstdc++.so.6
Loaded /lib/x86_64-linux-gnu/libtinfo.so.6 at 0x7f619e961000
Loading library /lib/x86_64-linux-gnu/libtinfo.so.6
Loaded /lib/x86_64-linux-gnu/libxml2.so.2 at 0x7f619e9cb000
Loading library /lib/x86_64-linux-gnu/libxml2.so.2
Loaded /lib/x86_64-linux-gnu/libz.so.1 at 0x7f619e728000
Loading library /lib/x86_64-linux-gnu/libz.so.1
Loaded /lib64/ld-linux-x86-64.so.2 at 0x7f619ee93000
Loading library /lib64/ld-linux-x86-64.so.2
Loaded /usr/local/lib/libcob.so.4 at 0x7f619ee23000
Loading library /usr/local/lib/libcob.so.4
Loaded /usr/local/lib/libvbisam.so.3 at 0x7f619e930000
Loading library /usr/local/lib/libvbisam.so.3
Loaded linux-vdso.so.1 at 0x7ffcbffa6000
Loading library linux-vdso.so.1
The list of loaded libraries has been updated
Removing breakpoint at 0x55de7792c200 - old data: 0x8949ed31fa1e0fcc, new data : 0x8949ed31fa1e0ff3, orig_instr: f3
*** stack smashing detected ***: terminated

**Comment by mridoni** [comment]
I reproduced this, it seems it escaped the tests: unfortunately the automated tests are only performed on Windows, and this part is obviously platform-specific. I am working on it and I'm planning to include a fix in the next release (end of February, more or less).

**Comment by dev4inno** [comment]
Thank you for your fast response!
Can I use an older version in the meantime (1.0.6/1.0.5) if it is still available (download address?)?
Or is the bug in these versions as well?

**Comment by mridoni** [comment]
Older releases are available on the same page, but they probable share that problem. It seems to be a race condition in the debugger: I used a fresh Ubuntu 20.04 VM and sometimes it starts ok, most of the times it crashes or cannot attach to the process. Needless to say, on my Linux development machine (still a VM but way beefier than the first, and with a different version of Linux, it works flawlessly... :-( )

**Comment by dev4inno** [comment]
OK, then I will wait for the new bug-fixed version :-)
Thank you for your effort!

**Comment by mridoni** [comment]
This should be solved in [v1.0.8](https://github.com/mridoni/gix/releases/tag/v1.0.8)

**Comment by dev4inno** [comment]
Just downloaded - it works now :-)
Great job.
Thank you for this nice application!
