### ISSUE TITLE
gixsql: please add -V,--version

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#56]
That's quite a "common" one and the info is already in there - just show that instead of the help and error "-e must be used".

**Comment by mridoni** [comment]
Done, will be in v1.0.10

**Comment by GitMensch** [comment]
Implemented with 4baac0a.

**Comment by GitMensch** [comment]
I guess this was the case before and I've just not seen it: `gixpp --version` returns with an error code:

```sh
$> /opt/gixsql/bin/gixpp --version
gixpp - the ESQL preprocessor for Gix-IDE/GixSQL
Version: 1.0.11b
libgixpp version: 1.0.11b

$> echo $?
255

```

**Comment by mridoni** [comment]
Fixed in the internal repository
