### ISSUE TITLE
gixsql: please add gixpp wrapper for ocesql compat

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#57]
In the case of "only using gixsql" the complete gixpp is not needed.
To ease migrations from ocesql it would be nice to have a gixsql script (or if you want a binary) which would do something like:

```sh
#!/bin/bash
if test "x$2" == "x"; then
   gixpp $*
else
   input=$1; shift   
   output=$1; shift
   gixpp -e -I $(dirname $(readlink -f "$0"))/../lib/copy -i $input -o $output $*
fi
```

Note: that's an actually tested wrapper, when named "ocesql" and in PATH and next to the installed gixpp binary - works as real drop-in replacement  [apart from #56] :-)

**Comment by GitMensch** [comment]
Mentioned in https://github.com/mridoni/gix/releases/tag/v1.0.10, so may be closed - but where is the actual wrapper in this repo?

**Comment by mridoni** [comment]
It's here:
https://github.com/mridoni/gix/blob/main/deploy/installers/linux/gixsql-autoconf/misc/gixsql-wrapper

It gets copied by the exec-install-hook in the top-level Makefile.am:
https://github.com/mridoni/gix/blob/main/deploy/installers/linux/gixsql-autoconf/Makefile.am:

    install-exec-hook:
	cp misc/gixsql-wrapper $(prefix)/bin/gixsql && \
		chmod 755 $(prefix)/bin/gixsql
