### ISSUE TITLE
Suggestion for improvement: new option "Save before build" in Settings

### ISSUE THREAD

**Issue by dev4inno** [mridoni/gix#60]
Dear Marco,

only a small suggestion for improvement ...

I am working with several other IDE's like Geany, NetBeans or SAP Workbench.
These IDE's show a different behavior: when I invoke the Build function in these applications the current source from the editor will be taken and not the source that has been saved a while ago.

In other words: the current source is saved before the build process.
For me this speeds up the development process significantly because you can no longer forget to save the source before building it.

My proposal would be to add this option in the general settings:

![Gix_IDE_Settings](https://user-images.githubusercontent.com/63194871/156246578-b045573c-79ae-4e2d-80c9-f0323a574f50.jpg)

So you can achieve both behaviors by checking or unchecking this option.

**Comment by mridoni** [comment]
This will be in 1.0.10

**Comment by GitMensch** [comment]
Is implemented according to https://github.com/mridoni/gix/releases/tag/v1.0.10 - @dev4inno you may want to recheck and close the issue.

**Comment by dev4inno** [comment]
Dear Marco,

just tested, it works perfectly!
Also the other way round, when unchecking the option - I made a negative test as well.
Thank you for this improvement, it makes the development with Gix-IDE more productive.
What you see is what you build :-)

Kind regards from Northern Germany,
Klaus
