### ISSUE TITLE
gixsql-autoconf: possibly wrong folder for copybooks?

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#62]
https://github.com/mridoni/gix/blob/abe9b1955851e851957cf17d64ca319c2e8071f9/deploy/installers/linux/gixsql-autoconf/Makefile.am#L19

So it is currently prefix/lib/copy - shouldn't it be prefix/share/gix/copy?

**Comment by mridoni** [comment]
This is a compromise to keep the same layout in Linux and Windows (where a "share" directory is not normally part of the layout). I have to fix a few things in all the Linux+autoconf stuff, and since this can be handled with some compile-time defines in the IDE, I am adding this in the next release.

**Comment by GitMensch** [comment]
I'm a bit confused here. Do you say that it will be fixed in the "near current" 1.0.10? I _guess_ that you've meant "the version after" - so this would be milestone v1.0.11 or similar?

**Comment by mridoni** [comment]
I am taking (at last) all of this week to perform final tests and packaging, including the "autoconf" one so, yes, this will be in v1.0.10. By the way: this is my actual first dalliance with autotools, so I was expecting some hiccups. Thanks for your work and suggestions, always appreciated.

**Comment by GitMensch** [comment]
> By the way: this is my actual first dalliance with autotools, so I was expecting some hiccups.

Then actually done well so far. #52 and #54 will likely help a bit.

**Comment by GitMensch** [comment]
Fixed with 4baac0a - https://github.com/mridoni/gix/blob/4baac0a03625eb8e97e6f9a4437f4400e4b97b43/deploy/installers/linux/gixsql-autoconf/Makefile.am#L19
