### ISSUE TITLE
Bug: unexpected SELECTFROM - statements with sub-selects cannot be parsed

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#66]
```sql
          EXEC SQL AT :DBS
             SELECT
                TABROWID INTO :TABROWID FROM TAB1 
             WHERE
                HISTID = (SELECT MAX(HISTID) FROM TAB1 WHERE
                           REFNR         = :TAB1REFNR)
           END-EXEC.
```

>  error: syntax error, unexpected SELECTFROM

(BTW: likely another token that should get a literal, in this case "FROM")

**Comment by mridoni** [comment]
Fixed in my internal repository, I need to write a complete test case (the one I am using is preprocess+compile-only), but it will definitely be in v1.0.11

**Comment by GitMensch** [comment]
Looks like all files that previously error'd in the preprocessing with that now preprocess.

**Comment by GitMensch** [comment]
I'm not sure if this is a side-issue from another one, but in a test environment that does not use the multi-connection `AT` I see this again:

```sql
           EXEC SQL
              SELECT LEN FROM TAB INTO :LEN WHERE OID=:OID
           END-EXEC.
           EXEC SQL
               SELECT lo_close (DESCRIPTOR) FROM TAB
                      WHERE OID=:OID
           END-EXEC.
```

both raise

> error: syntax error, unexpected SELECTFROM

**Comment by mridoni** [comment]
Yes, I found this also when working on #89, with a sample query I am using. Working on it.
