### ISSUE TITLE
Add something like EXEC SQL COMMENT ... to be able to mark a code block as "don't parse anything in here"

### ISSUE THREAD

**Issue by mridoni** [mridoni/gix#73]
> Would it be possible/reasonable to add something like EXEC SQL COMMENT 100 lines of code EXEC SQL END to be able to mark a code block as "don't parse anything in here" (= the first one starts a lexer case where everything is just copied "as is")?

For the sake of clarity I am tracking this as a separate issue

_Originally posted by @mridoni in https://github.com/mridoni/gix/issues/50#issuecomment-1072162825_

**Comment by mridoni** [comment]
Already implemented, just needs further testing, will be in v1.0.11

**Comment by mridoni** [comment]
Testing finished, the text case also checks GnuCOBOL preprocessor directives support

**Comment by GitMensch** [comment]
Second thought: wouldn't an "implied" `exec sql comment` outside of any `EXEC SQL` - possibly only activated with a flag to gixpp - would solve all issues of "gixsql stumbles over something it doesn't understand but should not inspect in the first place"?

**Comment by GitMensch** [comment]
ping @mridoni about that "second thought" (handle everything outside of `EXEC SQL` as comment, possibly with an extra flag passed to gixpp).
