### ISSUE TITLE
gixpp (for gixsql) serious bug: outputs too many periods - breaks code flow

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#82]
TPESQLProcessing.cpp inserts the functions via `put_call()`, which takes a `bool terminate_with_period`.
That's fine so far, but the callers always use `stmt->period` as parameter, which is wrong for statements that are resolved by multiple `CALL`s.

Taken the simple code

```cobol
           IF SPECIAL-CASE
               EXEC SQL AT :DBS
                  SELECT something INTO :SOMETHING
               END-EXEC.
```

we correctly get a statement with `stmt->period == true`, and because of the preprocessing using it for any statements get a wrong code-flow:

```cobol
           IF SPECIAL-CASE
GIXSQL*        EXEC SQL AT :DBS
GIXSQL*           SELECT something INTO :SOMETHING
GIXSQL*        END-EXEC.
GIXSQL     CALL "GIXSQLStartSQL"
GIXSQL     END-CALL.
GIXSQL     CALL "GIXSQLSetResultParams" USING
GIXSQL         BY VALUE 16
GIXSQL         BY VALUE 26
GIXSQL         BY VALUE 0
GIXSQL         BY VALUE 0
GIXSQL         BY REFERENCE SOMETHING
GIXSQL     END-CALL.
GIXSQL     CALL "GIXSQLExecSelectIntoOne" USING
GIXSQL         BY REFERENCE SQLCA
GIXSQL         BY REFERENCE DBS
GIXSQL         BY VALUE 10
GIXSQL         BY REFERENCE SQ0012
GIXSQL         BY VALUE 0
GIXSQL         BY VALUE 1
GIXSQL     END-CALL.
GIXSQL     CALL "GIXSQLEndSQL"
GIXSQL     END-CALL.
```

As this is a multi-`put_call` statements _only_ the last one should use `stmt->period`, all previous must pass `false`. This is easy to fix for statements that use `put_start_exec_sql`, but there may be more places.

**Comment by mridoni** [comment]
I imported your fix, applied it to my internal repository and reviewed it, I confirm it seems fine.

Thanks
