### ISSUE TITLE
gixsql: please pass postgres cast operator as token

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#93]
An explicit cast via function works fine, but when using the PostgreSQL specific cast operator the preprocessor partially tries to resolve it.

Example:

`SELECT :VAR1::numeric FROM TAB WHERE :VAR2::numeric = 10`

currently leads to

> error: Cannot find host variable
> error: An error occurred while generating ESQL cursor declarations

Side note: please adjust the error message to output the variable gixpp searches, in this case

> error: Cannot find host variable "VAR1::numeric"

That helps a lot in checking where issues exist (commonly: where a typo was).

**Comment by mridoni** [comment]
Shouldn't the query be something like this?

                SELECT VAR1::numeric 
                    INTO :VAR1
                    FROM TAB 
                        WHERE :VAR2::numeric = 10

It has been fixed in this form and will be in v1.0.11b/v1.0.12.

**Comment by GitMensch** [comment]
Yes, that would be the correct form for my example. Rechecked: the code actually was used in a `DECLARE`:

```sql
           EXEC SQL
              DECLARE CK08 CURSOR FOR
                 SELECT VAR1 FROM TAB
                 WHERE
                    KVAR08 >= (
                        CASE WHEN :VAR2::numeric < 0 THEN
                           'A' || TO_CHAR(999999.9999999 +
                                          :VAR2::numeric,
                                          'FM000000D0000000')
                        ELSE
                           'B' || TO_CHAR(0 +
                                          :VAR2::numeric,
                                          'FM000000D0000000')
                        END
                     || CASE WHEN :VAR3::numeric < 0 THEN
                           'A' || TO_CHAR(999999.9999999 +
                                          :VAR3::numeric,
                                          'FM000000D0000000')
                        ELSE
                           'B' || TO_CHAR(0 +
                                          :VAR3::numeric,
                                          'FM000000D0000000')
                        END
                             )
                 ORDER BY KVAR08 ASC
           END-EXEC.
```

:-)

I assume that works with v1.0.11b/v1.0.12, too; leaving only #92 and possibly #43 for 1.0.11b, correct?

**Comment by mridoni** [comment]
More or less yes: #92 is fixed in my internal repository, #43 is being worked on and wiill take a little more

**Comment by GitMensch** [comment]
Tested 1.0.11b with the sample above and get

>  error: Cannot find host variable

rechecked with the debugger: the hostvariable checked is ":" and therefore its substr(1) is "" and we don't see an error here.
Checking the line number with the debugger (#69) is the one that reads `|| CASE WHEN :VAR2::numeric < 0 THEN`.

**Comment by mridoni** [comment]
Fixed in the internal repository

**Comment by GitMensch** [comment]
Looks solved to me :-)
