### ISSUE TITLE
Question: How to run/debug a program which calls a C subprogram

### ISSUE THREAD

**Issue by dev4inno** [mridoni/gix#95]
Hello Marco,

just a handling question:

I would like to run a program which calls a C subprogram (wrapper for Gtk GUI) in Gix-IDE.
Please find the program attached as zip file and a PDF document showing the Gix-IDE message.

The compile needs to be done with this command:
cobc -x `pkg-config --libs gtk+-3.0` gtkhello.cbl gcgtk.o

I do not know how to achieve this in Gix-IDE.

Kind regards from Northern Germany,
Klaus
[Gix-IDE_with_C_call.pdf](https://github.com/mridoni/gix/files/8400135/Gix-IDE_with_C_call.pdf)
[gtkhello.zip](https://github.com/mridoni/gix/files/8400138/gtkhello.zip)

**Comment by mridoni** [comment]
Hello,
as you already tried to, you should use the additional compile/link flags. I say "should" because unfortunately, due to a bug, these are currently ignored. I am working on a fix and tracking it for inclusion in the next release (hopefully 1.0.12).

**Comment by mridoni** [comment]
Just a word of caution: the additional arguments (for compiler and linker) will be used literally anyway, so you will not be able to use shell sub-commands in there (e.g. `pkgconfig`). In your example this means you will have to compile the bindings separately, not with Gix-IDE, and then link to it. 

Ideally it would be nice to have external objects (and build commands for them) as dependencies of a project but this is not planned yet.

**Comment by mridoni** [comment]
I developed a fix and it works, you will also have to set the proper working directory (otherwise the application will not be able to find the `frmhello.xml` file). This will definitely be in v1.0.12.

![image](https://user-images.githubusercontent.com/16079316/161378337-c9cd8886-aeb5-45b5-b242-df581446042e.png)

**Comment by dev4inno** [comment]
Ciao Marco,

thank you for ultra fast response.

Your screenshot looks great!

And yes: I am aware of the fact, that I need to compile the C bindings separately.

Is there a setting for the working directory in Gix-IDE or do I need to set the path within my COBOL source?
Maybe you can provide me with the correct settings to get gtkhello.cbl to run when v1.0.12 is out.

I am eagerly awaiting the new release v1.0.12 :-)

Thank you for this great application & Kind regards,
Klaus

**Comment by mridoni** [comment]
> Is there a setting for the working directory in Gix-IDE or do I need to set the path within my COBOL source?

Yes, it's there in the project settings, I had to fix this too because it wasn't working under Linux (it is now and the fix will be in 1.0.12).

**Comment by dev4inno** [comment]
Dear Marco,

very delighted I have seen that the new version v1.0.12 is available :-)
Just installed it right away on my Linux box.

I found the setting for the working directory but I do not know where (and how) to specify the compile/link parameters in Gix-IDE.

As I saw from your screenshot above you were able to compile and run my gtkhello.cbl example.

Could you please advise me how the additional compiler/linker parameters should look like and where I have to put them in project properties?

That would be great.

Ciao,
Klaus

**Comment by mridoni** [comment]
Hello Klaus,
you will find them in the Properties window, after selecting the project in the Project Collection window:

![image](https://user-images.githubusercontent.com/16079316/162462065-b4350aa6-e953-49b9-b0df-128b75c11ce2.png)

To run your sample, in "Additional C linker options" I have set:

`-L .-lgcgtk -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0`

(Note: the machine where I tested has a KDE Neon distribution installed, so the package names might be slightly different)

**Comment by dev4inno** [comment]
Hello Marco,

thank you - looks much better now. I am able to compile/link it.

But when I try to run the program I get this error in the Console windows:

libcob: /home/haegar/gix/gtkhello/gtkhello.cbl:53: Fehler: module 'CBL_OC_GTK_INIT_CHECK' not found
 Last statement of gtkhello was at line 53 of /home/haegar/gix/gtkhello/gtkhello.cbl
 
My source directory is /home/haegar/gix/gtkhello and it includes the bindings (gcgtk) in .o and .so version:

![gtkhello_001](https://user-images.githubusercontent.com/63194871/162470268-127f60c1-6b44-48a9-920d-422fd58d199c.png)

I have also put the bindings into /home/haegar/gix/gtkhello/bin/debug/x64, but the error still occurs.

Am I missing something?

Ciao,
Klaus

**Comment by mridoni** [comment]
> Am I missing something?

No, but I did: to run your program from the IDE, you have to go in the Properties section, and add an entry in "Run/Debug Environment" for LD_PRELOAD,like this (obviously with the correct path):

![image](https://user-images.githubusercontent.com/16079316/162474893-3d407cd0-3c8d-4843-bcee-174e08e9b414.png)

This probably can be solved in another way, without having to use LD_PRELOAD, but I have to check the linker options.

**Comment by dev4inno** [comment]
OK, tried your above option.
This gives me the error:

/home/haegar/gix/gtkhello/bin/debug/x64/gtkhello: symbol lookup error: /home/haegar/gix/gtkhello/gcgtk.so: undefined symbol: gtk_init_check

**Comment by dev4inno** [comment]
> Either use a `CALL STATIC` to these functions and link the gcgtk.so in (or link the gcobject.o) or have that library in `COB_LIBRARY_PATH` and use `COB_PRELOAD=gcgtk` to load it on runtime start (commonly my favorite).

Hello Simon: Marco seems to have managed it in another way (as you can see from his screenshot above). Maybe gcgtk only needs to be linked with another parameter?

**Comment by dev4inno** [comment]
Finally I was able to run the program by creating the shared library with this command:
`gcc -shared -o gcgtk.so gcgtk.o ``pkg-config --libs gtk+-3.0`` `


(see: https://stackoverflow.com/questions/19934889/undefined-symbols-in-so-after-compiling-despite-supplying-libs)

BUT: I am not able to debug the program - all Breakpoints are ignored ...

![Auswahl_001](https://user-images.githubusercontent.com/63194871/162483499-b13ca792-e2e1-4cfe-b701-463f90aad822.png)

Any ideas?

**Comment by mridoni** [comment]
I have to check this and then I'll get back to you

**Comment by mridoni** [comment]
Found: the fix for the working directory in Linux unfortunately introduced a regression that causes a problem with the debugger. I will publish a patch for this as soon as I can, probably in the first days of the next week.

**Comment by dev4inno** [comment]
> 

Great!
And: no problem - I am waiting since years for a tool like this, so some days do not matter :-)
Have a nice weekend,
Klaus

**Comment by mridoni** [comment]
The "working directory thing" is fixed but I found a couple more things in the Linux debugger that need to be fixed, I will keep you all opsted.

**Comment by dev4inno** [comment]
Only a suggestion: if you're already applying changes in this area, maybe you can also make the picture clause case insensitive.
As I told you in a previous post, a lower case pic x (instead of pic X) causes undefined values (??) in the Watch window.

That would be great!

**Comment by mridoni** [comment]
> Only a suggestion: if you're already applying changes in this area, maybe you can also make the picture clause case insensitive. As I told you in a previous post, a lower case pic x (instead of pic X) causes undefined values (??) in the Watch window.

I'll see if I can find a quick fix, the problem is that the parser is currently not really uppercase-friendly, so there is a lot more to be done in that area and probably many more quirks of this type. But we'll get there... :-)

**Comment by dev4inno** [comment]
Dear Marco,

delighted I just saw that the new version is available.
Immediately I installed both packages Gix-IDE and GixSQL in the new version v1.0.13.
Unfortunately I cannot start Gix-IDE.

I got this error:

/opt/gix-ide/bin/gix-ide: error while loading shared libraries: libgixsql.so.1: cannot open shared object file: No such file or directory

And: I tried it on my Ubuntu 20.04 box as well on my Debian 11 PC. The result was the same on both machines.
I also issued a ldconfig command without any effect.

Maybe a symlink is missing?

Ciao,
Klaus

**Comment by dev4inno** [comment]
Just to add: I also deinstalled the existing versions of Gix-IDE and GixSQL completely and reinstalled them.
But the error remains.

**Comment by mridoni** [comment]
Hello Klaus,
this seems a problem with the packaging script that left out a few files, I'll sort it out in the next release. In the meantime you can try this (it worked on my test machine):

`sudo cp /opt/gix-ide/lib/x64/gcc/libgixsql* /opt/gix-ide/bin`

Explanation: there are a couple of levels of subdirectories under the `lib` directory of Gix-IDE because you could (in theory) compile and run programs:

1. with compilers other than GCC (using a different runtime or library format)
2. compile/run/debug for a different architecture (e.g. x86 instead of x64)

This means that different version of the runtime libraries for GixSQL have to be deployed.

In practice:

1 is only possible on Windows (MinGW vs MSVC)
2 is only theoretical because the debugger at the moment can only be used under the architecture it was compiled for (under Linux the binaries packages are x64-only).

This means that for now on Linux there is one and only one version of the GixSQL runtime libraries, so it is enough to copy them in the right place.

**Comment by dev4inno** [comment]
Hello Marco,

thank you for your response.

After copying the runtime library with your above command I am able to start Gix-IDE again.
But the breakpoints are still ignored in the gtkhello program.
Now I get several messages "Cannot resolve data for module gtkhello" in the output window.
Will that be fixed in the next (v1.0.14) release?

Happy Easter!

Ciao
Klaus

**Comment by mridoni** [comment]
After applying this workaround I specifically checked the debugger, and it was working, so there must be something else. That message implies that the debugger cannot load the debugging symbols at some stage. Could you cut and paste here the text from the Output window (after ensuring that “show debug output” in Settings is checked)? I’ll look into it in the next few days.

Thanks

**Comment by dev4inno** [comment]
Hello Marco,

here it is:

Starting to build gtkhello.gix for target debug/x64
Building /home/haegar/gix/gtkhello.gix
${prj.output_path}/gtkhello IS NOT UP TO DATE (0)
Ide status set to 3 (Building)
[
    target_filename : /home/haegar/gix/gtkhello.gix
    build_action    : 
    optional        : false
    virtual         : true
    target_provides : 
    target_uses     : singleartifact/dll,multiartifact/dll,singleartifact/exe,multiartifact/exe,webartifact/dll
    has_ownership   : false
    item            : {00007f4e-0018-0000-0000-000054006900}
    dependencies    : [
        target_filename : /home/haegar/gix/gtkhello/bin/debug/x64/gtkhello
        build_action    : link
        optional        : false
        virtual         : false
        target_provides : exe
        target_uses     : obj
        has_ownership   : false
        item            : {00000000-4df0-92c7-8055-00004031cb92}
        dependencies    : [
            target_filename : /home/haegar/gix/gtkhello/bin/debug/x64/gtkhello.o
            build_action    : compile
            optional        : false
            virtual         : false
            target_provides : obj
            target_uses     : cbl
            has_ownership   : false
            item            : {00007f4e-0018-0000-0000-000041006d00}
            dependencies    : [
                target_filename : /home/haegar/gix/gtkhello/gtkhello.cbl
                build_action    : none
                optional        : false
                virtual         : false
                target_provides : cbl
                target_uses     : 
                has_ownership   : false
                item            : {00007f4e-0018-0000-0000-000041006d00}
                dependencies    : [
                ]
            ]
        ]
    ]
]

/home/haegar/gix/gtkhello/gtkhello.cbl IS UP TO DATE
/home/haegar/gix/gtkhello/bin/debug/x64/gtkhello.o IS UP TO DATE
/home/haegar/gix/gtkhello/bin/debug/x64/gtkhello IS UP TO DATE
Ide status set to 2 (Editing)
Ide status set to 7 (Starting)
Scanning /home/haegar/gix/gtkhello/gtkhello.cbl
Finished scanning /home/haegar/gix/gtkhello/gtkhello.cbl
DataWindow is refreshing
DataWindow is refreshing
Setting up console
Symbols loaded

Program /home/haegar/gix/gtkhello/bin/debug/x64/gtkhello started
Process started (2676)
:: Loaded symbols for /home/haegar/gix/gtkhello/bin/debug/x64/gtkhello
/home/haegar/gix/gtkhello/bin/debug/x64/gtkhello is a GnuCOBOL module
Installing startup hardware breakpoint for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Debugger has loaded symbols and is ready to run /home/haegar/gix/gtkhello/bin/debug/x64/gtkhello
Ide status set to 4 (Debugging)
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Cannot resolve data for module gtkhello
Program /home/haegar/gix/gtkhello/bin/debug/x64/gtkhello terminated with result code: 0
:: EXIT CODE: 0
Activated window for /home/haegar/gix/gtkhello/gtkhello.cbl
Process finished with exit code 0 (0x00000000)
Stopping debug driver
Ide status set to 2 (Editing)

As I told you before: when I push the Debug button the program runs through and ignores all the breakpoints.

Ciao
Klaus

**Comment by mridoni** [comment]
Thanks, I will look into it in the next few days.

**Comment by mridoni** [comment]
I checked using your original source and just added the "LD_PRELOAD=...", set the working directory and the linker flags. Unfortunately I cannot reproduce it, and the debugger, as expected, stops at breakpoints.

When you can, could you please attach here a zip with your current project folder? Just in case I have missed something.

Thanks for your patience.

**Comment by dev4inno** [comment]
[gixtest.zip](https://github.com/mridoni/gix/files/8501314/gixtest.zip)
Hello Marco,
no problem - here's a zip file with my complete gixtest folder containing the gtkhello project.
As I told you: I have removed and reinstalled Gix-IDE and GixSQL and also recreated the project from scratch, but the breakpoints are ignored since version v1.0.12 on both: my Ubuntu 20.04 and my Debian 11 box.
From my side as well: Thanks for your patience!
Ciao
Klaus

**Comment by mridoni** [comment]
Ok, I reproduced it, apparently it works correctly on my main Linux development machine but not on my test VM (Ubuntu 20.04). I'll look into it further in the next few days.

Thanks

**Comment by mridoni** [comment]
Found. It was actually a packaging bug: after the repository split some files were not being updated properly, so the changes between 1.0.12 and 1.0.13 were never packaged. I'll release 1.0.14 in a couple of days, just need some time to re-test again. Sorry for the inconvenience.

**Comment by dev4inno** [comment]
Perfect.
Thank you for your investigation.
And: no problem, I can wait.
Have a nice evening,
Klaus

**Comment by GitMensch** [comment]
Can I suggest to use rpath linking for the distributed gix binaries?
If both are installed from the deb package they would reside in those folders and using roast during linking would tell the gix binaries to look for the files in the sql place - no need to package them in the guy package, too.

**Comment by mridoni** [comment]
> Can I suggest to use rpath linking for the distributed gix binaries?

rpath is already set (to the copy of the library in the bin directory) but I' d like to keep these libraries separate from the runtime ones anyway, essentially for two reasons:

- keeping as much as possible the application layout consistent between Windows and Linux
- allowing for IDE-specific modifications in the future, given also that GixSQL has been moved into its own repository.

**Comment by GitMensch** [comment]
Isn't it possible to have two rpath entries?

**Comment by mridoni** [comment]
Yes, of course, but I would like to keep the two copies separate anyway for the reasons I mentioned above: it admittedly wastes a few hundred KBs  but makes things a bit easier for me. This is probably going to change in the future: when things are more stable, both with GixSQL and the IDE, I will probably switch to a more conventional install location for the .deb packages (`/usr` instead of `/opt` prefix) and, depending on the status of the parser at that point, this might change for good.

**Comment by dev4inno** [comment]
Hello Marco,
thank you for the new release v1.0.14!
Just installed it in my Ubuntu 20.04 box and the breakpoints are working now.
So I will close this bug now.
Thanks again and have a nice day,
Klaus
